language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -r requirements.txt"
services: 
- postgresql
before_script:
  - psql -c "create database travisdb;" -U postgres
script:
  - cd landing && python manage.py test