language: python
python:
  - "2.7"
services: 
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - cd demo && python manage.py syncdb --noinput
script:
  - cd demo && python manage.py test