language: python
python:
  - "2.7"
env:
  global:
    - POSTGRES_URL='postgres://postgres:postgres@localhost:5432/travis_ci_test' 
services: 
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - cd demo && python manage.py syncdb --noinput
script:
  - python manage.py test